# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.box = "bento/ubuntu-20.10"

	# Provision
	config.vm.provision :shell, :path => "install.sh"

	# To access a website running on port 8087 from the host, we can open a web browser  
	# and go to http://192.168.0.102:8087
	config.vm.network :forwarded_port, guest: 8087, host: 8087

	# vNIC
	config.vm.network "public_network", ip: "192.168.0.102"

	# Shared folder
	config.vm.synced_folder "vagrant/", "/home/vagrant", create: true

end